const LANGUAGES = [
  { name: 'English', value: 'English' },
  { name: 'Spanish', value: 'Spanish' },
  { name: 'French', value: 'French' },
  { name: 'Chinese (Mandarin)', value: 'Chinese (Mandarin)' },
  { name: 'Hindi', value: 'Hindi' },
  { name: 'Arabic', value: 'Arabic' },
  { name: 'Russian', value: 'Russian' },
  { name: 'Japanese', value: 'Japanese' },
  { name: 'German', value: 'German' },
  { name: 'Portuguese', value: 'Portuguese' },
  { name: 'Italian', value: 'Italian' },
  { name: 'Korean', value: 'Korean' },
  { name: 'Dutch', value: 'Dutch' },
  { name: 'Turkish', value: 'Turkish' },
  { name: 'Vietnamese', value: 'Vietnamese' },
  { name: 'Thai', value: 'Thai' },
  { name: 'Swedish', value: 'Swedish' },
  { name: 'Greek', value: 'Greek' },
  { name: 'Polish', value: 'Polish' },
  { name: 'Romanian', value: 'Romanian' },
];

const LOCATION = [
  { name: 'Argentina', value: 'Argentina' },
  { name: 'Australia', value: 'Australia' },
  { name: 'Austria', value: 'Austria' },
  { name: 'Bangladesh', value: 'Bangladesh' },
  { name: 'Belgium', value: 'Belgium' },
  { name: 'Brazil', value: 'Brazil' },
  { name: 'Canada', value: 'Canada' },
  { name: 'Chile', value: 'Chile' },
  { name: 'China', value: 'China' },
  { name: 'Colombia', value: 'Colombia' },
  { name: 'Czech Republic', value: 'Czech Republic' },
  { name: 'Denmark', value: 'Denmark' },
  { name: 'Egypt', value: 'Egypt' },
  { name: 'Finland', value: 'Finland' },
  { name: 'France', value: 'France' },
  { name: 'Germany', value: 'Germany' },
  { name: 'Greece', value: 'Greece' },
  { name: 'Hungary', value: 'Hungary' },
  { name: 'India', value: 'India' },
  { name: 'Indonesia', value: 'Indonesia' },
  { name: 'Ireland', value: 'Ireland' },
  { name: 'Italy', value: 'Italy' },
  { name: 'Japan', value: 'Japan' },
  { name: 'Kenya', value: 'Kenya' },
  { name: 'Malaysia', value: 'Malaysia' },
  { name: 'Mexico', value: 'Mexico' },
  { name: 'Morocco', value: 'Morocco' },
  { name: 'Netherlands', value: 'Netherlands' },
  { name: 'New Zealand', value: 'New Zealand' },
  { name: 'Nigeria', value: 'Nigeria' },
  { name: 'Norway', value: 'Norway' },
  { name: 'Pakistan', value: 'Pakistan' },
  { name: 'Peru', value: 'Peru' },
  { name: 'Philippines', value: 'Philippines' },
  { name: 'Poland', value: 'Poland' },
  { name: 'Portugal', value: 'Portugal' },
  { name: 'Qatar', value: 'Qatar' },
  { name: 'Romania', value: 'Romania' },
  { name: 'Russia', value: 'Russia' },
  { name: 'Saudi Arabia', value: 'Saudi Arabia' },
  { name: 'Singapore', value: 'Singapore' },
  { name: 'South Africa', value: 'South Africa' },
  { name: 'South Korea', value: 'South Korea' },
  { name: 'Spain', value: 'Spain' },
  { name: 'Sweden', value: 'Sweden' },
  { name: 'Switzerland', value: 'Switzerland' },
  { name: 'Thailand', value: 'Thailand' },
  { name: 'Turkey', value: 'Turkey' },
  { name: 'UAE', value: 'UAE' },
  { name: 'Ukraine', value: 'Ukraine' },
  { name: 'United Kingdom', value: 'United Kingdom' },
  { name: 'United States', value: 'United States' },
  { name: 'Vietnam', value: 'Vietnam' },
];

export const LANGUAGE_SELECT_OPTIONS = LANGUAGES.map((x) => ({
  label: x.name,
  value: x.name,
}));

export const LOCATION_SELECT_OPTIONS = LOCATION.map((x) => ({
  label: x.name,
  value: x.value,
}));
